# Generated by Django 4.2 on 2023-04-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=256)),
                ("img_path", models.ImageField(upload_to="")),
                (
                    "category",
                    models.CharField(
                        choices=[("offer", "구인"), ("search", "구직")], max_length=50
                    ),
                ),
                ("pets", models.CharField(max_length=50)),
                ("time", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
