# Generated by Django 4.2 on 2023-04-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
