# Generated by Django 4.2 on 2023-04-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='name',
            new_name='title',
        ),
    ]
