# Generated by Django 4.2 on 2023-04-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_pet_host",
            field=models.BooleanField(default=False),
        ),
    ]
