# Generated by Django 4.2 on 2023-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
        ),
        migrations.AlterField(
            model_name="commentmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
    ]
