# Generated by Django 4.2 on 2023-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="content",
            field=models.CharField(max_length=300),
        ),
    ]
