# Generated by Django 4.2 on 2023-04-13 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_alter_commentmodel_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentmodel",
            old_name="posts",
            new_name="post",
        ),
    ]
